import turtle,time
Louis = turtle.Turtle()
Louis.color("green")
Louis.forward(90)
time.sleep(2)
Louis.left(90)
Louis.forward(90)
time.sleep(2)
Louis.left(90)
Louis.forward(90)
time.sleep(2)
Louis.left(90)
Louis.forward(90)
time.sleep(2)
Louis.left(90)