import turtle,time
Louis = turtle.Turtle()
win = turtle.Screen()
win.title('維大力')
win.bgcolor('yellow')
Louis.color("green")
Louis.shape('turtle')
Louis.left(67)
Louis.forward(90)
time.sleep(2)
Louis.left(67)
Louis.forward(123)
time.sleep(2)
Louis.left(90)
Louis.forward(67)
time.sleep(2)
Louis.left(90)
Louis.forward(90)
time.sleep(1)
Louis.left(90)
Louis.forward(90)
time.sleep(1)
Louis.left(90)